trigger:
  - main

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - staging
      - prod

stages:
  - stage: validate
    jobs:
      - job: validate
        pool:
          name: 'my-agent'
        steps:
        - task: TerraformTaskV4@4
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: '<YOUR_BACKEND_SERVICE>'
            backendAzureRmResourceGroupName: '${{parameters.environment}}-rg-backend'
            backendAzureRmStorageAccountName: 'nik${{parameters.environment}}backendstorage'
            backendAzureRmContainerName: 'backendcontainer'
            backendAzureRmKey: '${{parameters.environment}}.terraform.tfstate'
        - task: TerraformTaskV4@4
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
        - task: TerraformTaskV4@4
          displayName: terraform fmt
          inputs:
            provider: 'azurerm'
            command: 'custom'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: '<YOUR_BACKEND_SERVICE>'

  - stage: plan
    dependsOn: validate
    condition: succeeded()
    jobs:
      - job: plan
        pool:
          name: 'my-agent'
        steps:
        - task: TerraformTaskV4@4
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: '<YOUR_BACKEND_SERVICE>'
            backendAzureRmResourceGroupName: '${{parameters.environment}}-rg-backend'
            backendAzureRmStorageAccountName: 'nik${{parameters.environment}}backendstorage'
            backendAzureRmContainerName: 'backendcontainer'
            backendAzureRmKey: '${{parameters.environment}}.terraform.tfstate'
        - task: TerraformTaskV4@4
          displayName: Terraform Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: '<YOUR_BACKEND_SERVICE>'
            commandOptions: '-var-file=${{parameters.environment}}.tfvars'

  - stage: deploy
    dependsOn: plan
    condition: succeeded()
    jobs:
      - deployment: Deploy
        environment: terraform-apply
        pool:
          name: 'my-agent'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: TerraformTaskV4@4
                displayName: terraform init
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: '<YOUR_BACKEND_SERVICE>'
                  backendAzureRmResourceGroupName: '${{parameters.environment}}-rg-backend'
                  backendAzureRmStorageAccountName: 'nik${{parameters.environment}}backendstorage'
                  backendAzureRmContainerName: 'backendcontainer'
                  backendAzureRmKey: '${{parameters.environment}}.terraform.tfstate'
              - task: TerraformTaskV4@4
                displayName: Terraform Apply
                inputs:
                  provider: 'azurerm'
                  command: 'apply'
                  commandOptions: '-var-file=${{parameters.environment}}.tfvars --auto-approve'
                  environmentServiceNameAzureRM: '<YOUR_BACKEND_SERVICE>'
